/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Locadora;

import Locadora.Classe.ConexaoBanco;
import Locadora.View.Menu;

public class App {
    
    

  public static void main(String[] args) {
        // Chamar o método main da classe Menu
        Menu.main(args);
        
        
        
        
    }
}
