/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Locadora.View;

import Locadora.Model.Fabricante;
import Locadora.Services.FabricanteServices;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.ImageObserver;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rodrigo Ortolani
 */
public class CadastroFabricantes extends javax.swing.JFrame {
     private List<String> nomesFabricantes;

// Construtor que recebe a lista de nomes de fabricantes como argumento
public CadastroFabricantes(List<String> nomesFabricantes) {
    this.nomesFabricantes = nomesFabricantes;
    initComponents(); // Chama o método para inicializar os componentes da interface gráfica
    adicionarNomesFabricantes(); // Adiciona os nomes dos fabricantes à lista gráfica
    setBackgroundImage(); 
        setLocationRelativeTo(null); // Define a posição da janela para o centro da tela
        setResizable(false);
    // Adiciona um ComponentListener para atualizar a imagem de fundo quando o JFrame for redimensionado
    addComponentListener(new ComponentAdapter() {
        @Override
        public void componentResized(ComponentEvent e) {
            setBackgroundImage();
        }
    });

    // Definir o layout do JFrame como null para remover as bordas superior e inferior
    getContentPane().setLayout(null);
}


    // Construtor vazio removido

    private void adicionarNomesFabricantes() {
            list1.removeAll();

    // Obtém a lista de fabricantes com seus IDs
    List<Fabricante> fabricantes = new FabricanteServices().consultar();

    // Adiciona os nomes dos fabricantes à lista gráfica
    for (Fabricante fabricante : fabricantes) {
        // Formata a string para exibir o ID e o nome do fabricante
        String fabricanteString = String.format("%d - %s", fabricante.getId(), fabricante.getNome());
        list1.add(fabricanteString); // Adiciona o fabricante à lista
    }
}

    /**
     * Creates new form CadastroFabricantes
     */
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        txtDigiteNomeFabricante = new javax.swing.JTextField();
        BtnCadastroFabricante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTNAtualizarLista = new javax.swing.JButton();
        BtnVoltarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        txtDigiteNomeFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigiteNomeFabricanteActionPerformed(evt);
            }
        });

        BtnCadastroFabricante.setText("Cadastrar");
        BtnCadastroFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastroFabricanteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));

        BTNAtualizarLista.setText("Atualizar Lista");
        BTNAtualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAtualizarListaActionPerformed(evt);
            }
        });

        BtnVoltarMenu.setText("Menu");
        BtnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCadastroFabricante)
                            .addComponent(txtDigiteNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNAtualizarLista)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(BTNAtualizarLista)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(txtDigiteNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCadastroFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(BtnVoltarMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
 

// Classe para exibir uma imagem de fundo em um JPanel
class ImagePanel extends JPanel {
    private Image image;

    // Construtor que recebe o caminho da imagem
    public ImagePanel(String imagePath) {
        image = new ImageIcon(imagePath).getImage();
    }

    // Sobrescreve o método paintComponent para desenhar a imagem no JPanel
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
    }

    // Sobrescreve o método getPreferredSize para definir o tamanho preferido do JPanel
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(image.getWidth(this), image.getHeight(this));
    }
}

    
private void setBackgroundImage() {
    // Caminho absoluto para a imagem
    String imagePath = "C:\\Users\\Rodrigo Ortolani\\Documents\\NetBeansProjects\\Locadora-de-Ve-culos-main\\app\\src\\main\\java\\Locadora\\View\\Imagens\\fabricanteslogos.jpg";


    try {
        // Carrega a imagem
        Image image = new ImageIcon(imagePath).getImage();

        // Verifica se a imagem foi carregada corretamente
        if (image != null) {
            // Redimensiona a imagem para caber no JFrame
            int contentWidth = getContentPane().getWidth();
            int contentHeight = getContentPane().getHeight();
            Image scaledImage = image.getScaledInstance(contentWidth, contentHeight, Image.SCALE_SMOOTH);

            // Cria um ImageIcon com a imagem redimensionada
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            // Cria um JLabel para exibir a imagem
            JLabel backgroundLabel = new JLabel(scaledIcon);
            backgroundLabel.setBounds(0, 0, contentWidth, contentHeight);

            // Adiciona o JLabel ao content pane do JFrame
            getContentPane().add(backgroundLabel);

            // Revalida e redesenha o content pane do JFrame para garantir que as mudanças sejam aplicadas
            revalidate();
            repaint();
        } else {
            System.err.println("Erro ao carregar a imagem: " + imagePath);
        }
    } catch (Exception e) {
        e.printStackTrace();
        System.err.println("Erro ao carregar a imagem: " + imagePath);
    }
}


    
    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void txtDigiteNomeFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigiteNomeFabricanteActionPerformed
     
        
    }//GEN-LAST:event_txtDigiteNomeFabricanteActionPerformed

    private void BtnCadastroFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroFabricanteActionPerformed
      
            String nomeFabricante = txtDigiteNomeFabricante.getText(); // Obtém o nome do fabricante do campo de texto
    
    FabricanteServices fabricanteServices = new FabricanteServices();
    fabricanteServices.cadastrarFabricante(nomeFabricante);
        JOptionPane.showMessageDialog(rootPane,"Fabricante cadastrado com sucesso !!");
    }//GEN-LAST:event_BtnCadastroFabricanteActionPerformed

    private void BTNAtualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAtualizarListaActionPerformed
         this.dispose();
    
    // Cria uma nova instância da tela atual e a torna visível
    CadastroFabricantes cadastroFabricantes = new CadastroFabricantes(nomesFabricantes);
    cadastroFabricantes.setVisible(true);
    }//GEN-LAST:event_BTNAtualizarListaActionPerformed

    private void BtnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarMenuActionPerformed
         Menu menu = new Menu();
    
    // Tornar a instância do menu visível
    menu.setVisible(true);
    
    // Fechar a janela atual
    this.dispose();
        
        
    }//GEN-LAST:event_BtnVoltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    
    
    class ImagePanel extends JPanel {
    private Image image;

    // Construtor que recebe o caminho da imagem
    public ImagePanel(String imagePath) {
        image = new ImageIcon(imagePath).getImage();
    }

    // Sobrescreve o método paintComponent para desenhar a imagem no JPanel
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
    }

    // Sobrescreve o método getPreferredSize para definir o tamanho preferido do JPanel
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(image.getWidth((ImageObserver) this), image.getHeight((ImageObserver) this));
    }
}
    
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Obtém a lista de nomes de fabricantes
            List<String> nomesFabricantes = new FabricanteServices().obterNomesFabricantes();

            // Cria uma instância de CadastroFabricantes e passa a lista de nomes de fabricantes
            new CadastroFabricantes(nomesFabricantes).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAtualizarLista;
    private javax.swing.JButton BtnCadastroFabricante;
    private javax.swing.JButton BtnVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private java.awt.List list1;
    private javax.swing.JTextField txtDigiteNomeFabricante;
    // End of variables declaration//GEN-END:variables
}
