/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Locadora.View;

import Locadora.Model.Fabricante;
import Locadora.Services.FabricanteServices;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Ortolani
 */
public class CadastroFabricantes extends javax.swing.JFrame {
     private List<String> nomesFabricantes;

    // Construtor que recebe a lista de nomes de fabricantes como argumento
    public CadastroFabricantes(List<String> nomesFabricantes) {
              this.nomesFabricantes = nomesFabricantes;
        initComponents(); // Chama o método para inicializar os componentes da interface gráfica
        adicionarNomesFabricantes(); // Adiciona os nomes dos fabricantes à lista gráfica
    }

    // Construtor vazio removido

    private void adicionarNomesFabricantes() {
            list1.removeAll();

    // Obtém a lista de fabricantes com seus IDs
    List<Fabricante> fabricantes = new FabricanteServices().consultar();

    // Adiciona os nomes dos fabricantes à lista gráfica
    for (Fabricante fabricante : fabricantes) {
        // Formata a string para exibir o ID e o nome do fabricante
        String fabricanteString = String.format("%d - %s", fabricante.getId(), fabricante.getNome());
        list1.add(fabricanteString); // Adiciona o fabricante à lista
    }
}

    /**
     * Creates new form CadastroFabricantes
     */
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        txtDigiteNomeFabricante = new javax.swing.JTextField();
        BtnCadastroFabricante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTNAtualizarLista = new javax.swing.JButton();
        BtnVoltarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        txtDigiteNomeFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigiteNomeFabricanteActionPerformed(evt);
            }
        });

        BtnCadastroFabricante.setText("Cadastrar");
        BtnCadastroFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastroFabricanteActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite o nome do Fabricante  para cadastro");

        BTNAtualizarLista.setText("Atualizar Lista");
        BTNAtualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAtualizarListaActionPerformed(evt);
            }
        });

        BtnVoltarMenu.setText("Menu");
        BtnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(BtnVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtDigiteNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTNAtualizarLista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BtnCadastroFabricante)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVoltarMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDigiteNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAtualizarLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCadastroFabricante)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void txtDigiteNomeFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigiteNomeFabricanteActionPerformed
     
        
    }//GEN-LAST:event_txtDigiteNomeFabricanteActionPerformed

    private void BtnCadastroFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroFabricanteActionPerformed
      
            String nomeFabricante = txtDigiteNomeFabricante.getText(); // Obtém o nome do fabricante do campo de texto
    
    FabricanteServices fabricanteServices = new FabricanteServices();
    fabricanteServices.cadastrarFabricante(nomeFabricante);
        JOptionPane.showMessageDialog(rootPane,"Fabricante cadastrado com sucesso !!");
    }//GEN-LAST:event_BtnCadastroFabricanteActionPerformed

    private void BTNAtualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAtualizarListaActionPerformed
         this.dispose();
    
    // Cria uma nova instância da tela atual e a torna visível
    CadastroFabricantes cadastroFabricantes = new CadastroFabricantes(nomesFabricantes);
    cadastroFabricantes.setVisible(true);
    }//GEN-LAST:event_BTNAtualizarListaActionPerformed

    private void BtnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarMenuActionPerformed
         Menu menu = new Menu();
    
    // Tornar a instância do menu visível
    menu.setVisible(true);
    
    // Fechar a janela atual
    this.dispose();
        
        
    }//GEN-LAST:event_BtnVoltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(CadastroFabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Obtém a lista de nomes de fabricantes
            List<String> nomesFabricantes = new FabricanteServices().obterNomesFabricantes();

            // Cria uma instância de CadastroFabricantes e passa a lista de nomes de fabricantes
            new CadastroFabricantes(nomesFabricantes).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAtualizarLista;
    private javax.swing.JButton BtnCadastroFabricante;
    private javax.swing.JButton BtnVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private java.awt.List list1;
    private javax.swing.JTextField txtDigiteNomeFabricante;
    // End of variables declaration//GEN-END:variables
}
