/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Locadora.View;

import Locadora.Model.Fabricante;
import Locadora.Model.Modelo;
import Locadora.Repository.ModeloRepository;
import Locadora.Services.FabricanteServices;
import Locadora.Services.ModeloServices;
import java.awt.Color;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Rodrigo Ortolani
 */
public class CadastroModelos extends javax.swing.JFrame {

   private int idFabricanteSelecionado;
       private List<String> nomesFabricantes;
     
       
    public CadastroModelos(List<String> nomesFabricantes) {
        initComponents();
         adicionarNomesFabricantes(); 
    }
private void adicionarNomesFabricantes() {
             DefaultListModel<String> model = new DefaultListModel<>();

    // Obtém a lista de fabricantes com seus IDs
    List<Fabricante> fabricantes = new FabricanteServices().consultar();

    // Adiciona os nomes dos fabricantes ao modelo de lista
    for (Fabricante fabricante : fabricantes) {
        // Formata a string para exibir o ID e o nome do fabricante
        String fabricanteString = String.format("%d - %s", fabricante.getId(), fabricante.getNome());
        model.addElement(fabricanteString); // Adiciona o fabricante ao modelo
    }

    // Define o modelo na lista gráfica
    jListFABRICANTES.setModel(model);

    // Define um ouvinte de seleção para a lista de fabricantes
   jListFABRICANTES.addListSelectionListener(new ListSelectionListener() {
    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            // Obtém o índice do item selecionado na lista de fabricantes
            int selectedIndex = jListFABRICANTES.getSelectedIndex();
            if (selectedIndex != -1) {
                // Obtém o texto do item selecionado (formato: "ID - Nome")
                String selectedItem = (String) jListFABRICANTES.getSelectedValue();
                // Divide o texto para extrair o ID
                String[] parts = selectedItem.split(" - ");
                int fabricanteId = Integer.parseInt(parts[0]);
                // Aqui você pode usar o fabricanteId para associá-lo ao modelo
                // que o usuário está prestes a cadastrar
                System.out.println("ID do fabricante selecionado: " + fabricanteId);
                // Defina o ID do fabricante selecionado
                idFabricanteSelecionado = fabricanteId;
            }
        }
    }
});
    // Define a cor do texto na lista gráfica (opcional)
    jListFABRICANTES.setForeground(Color.BLACK);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListFABRICANTES = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        digiteModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTNCADASTRARMODELO = new javax.swing.JButton();
        BTNMENU = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BTNLISTADEMODELOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListFABRICANTES.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListFABRICANTES);

        jLabel1.setText("Fabricantes");

        digiteModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digiteModeloActionPerformed(evt);
            }
        });

        jLabel2.setText("Cadastro de Modelos");

        jLabel3.setText("Modelo:");

        BTNCADASTRARMODELO.setText("Cadastrar");
        BTNCADASTRARMODELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCADASTRARMODELOActionPerformed(evt);
            }
        });

        BTNMENU.setText("Menu Principal");
        BTNMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMENUActionPerformed(evt);
            }
        });

        jButton1.setText("Novo Fabricante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTNLISTADEMODELOS.setText("Lista de Modelos");
        BTNLISTADEMODELOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLISTADEMODELOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(BTNMENU))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNCADASTRARMODELO)
                                    .addComponent(digiteModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addComponent(BTNLISTADEMODELOS))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap(9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMENU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(digiteModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNCADASTRARMODELO))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNLISTADEMODELOS)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void digiteModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digiteModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digiteModeloActionPerformed

    private void BTNCADASTRARMODELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCADASTRARMODELOActionPerformed
        
String nomeModelo = digiteModelo.getText();
    if (!nomeModelo.isEmpty()) {
        if (idFabricanteSelecionado != 0) {
            // Crie um objeto Modelo com o nome do modelo e o ID do fabricante selecionado
          Modelo modelo = new Modelo(Long.MIN_VALUE, nomeModelo, Long.MAX_VALUE);

            // Chame o método salvar da classe ModeloRepository, passando o novo modelo como argumento
            ModeloRepository modeloRepo = new ModeloRepository();
            modeloRepo.salvarModelo(modelo);

            JOptionPane.showMessageDialog(rootPane,"Modelo Cadastrado com sucesso !!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecione um fabricante antes de cadastrar um modelo. Caso não contenha o fabricante na lista, por favor, clique em cadastrar fabricantes.");
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Por favor, informe o nome do modelo ");
    }
    }//GEN-LAST:event_BTNCADASTRARMODELOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastroFabricantes fabricantes = new CadastroFabricantes(nomesFabricantes);
        fabricantes.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMENUActionPerformed
        Menu menu = new Menu();

        // Tornar a instância do menu visível
        menu.setVisible(true);

        // Fechar a janela atual
        this.dispose();
    }//GEN-LAST:event_BTNMENUActionPerformed

    private void BTNLISTADEMODELOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLISTADEMODELOSActionPerformed

      
    

     ModeloServices modeloService = new ModeloServices();
    List<Modelo> modelos = modeloService.consultarTodosmodelos();
    
    StringBuilder mensagem = new StringBuilder();
    mensagem.append("Lista de Modelos:\n");
    mensagem.append("________________________________\n");
    for (Modelo modelo : modelos) {
        mensagem.append("ID: ").append(modelo.getId()).append(", ");
        mensagem.append("Modelo: ").append(modelo.getNome()).append(", ");
        mensagem.append("Fabricante: ").append(modelo.getNomeFabricante()).append("\n");
    }
    mensagem.append("________________________________");

        // Criando uma JTextArea para exibir a mensagem com barra de rolagem
        JTextArea textArea = new JTextArea(mensagem.toString());
        textArea.setEditable(false); // Impede que o usuário edite o texto
        JScrollPane scrollPane = new JScrollPane(textArea); // Adiciona a JTextArea a um JScrollPane

        // Exibe o diálogo JOptionPane com a JTextArea dentro do JScrollPane
        JOptionPane.showMessageDialog(null, scrollPane, "Lista de Modelos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BTNLISTADEMODELOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroModelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 List<String> nomesFabricantes = new FabricanteServices().obterNomesFabricantes();

            // Cria uma instância de CadastroFabricantes e passa a lista de nomes de fabricantes
            new CadastroFabricantes(nomesFabricantes).setVisible(true);
                
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCADASTRARMODELO;
    private javax.swing.JButton BTNLISTADEMODELOS;
    private javax.swing.JButton BTNMENU;
    private javax.swing.JTextField digiteModelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListFABRICANTES;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

