/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Locadora.View;

import Locadora.Model.Fabricante;
import Locadora.Services.FabricanteServices;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Ortolani
 */
public class DeletarFabricante extends javax.swing.JFrame {
    private final FabricanteServices fabricanteServices;
    private Object Locadora;
   
    /**
     * Creates new form DeletarFabricante
     */
    public DeletarFabricante() {
        initComponents();
                   setBackgroundImage(); 

           createMenuBar();
        setLocationRelativeTo(null); // Define a posição da janela para o centro da tela
        setResizable(false);
        fabricanteServices = new FabricanteServices();
        preencherComboBox();
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exibirNomeFabricanteSelecionado();
            }
        });
    
        
        
        
        
    }

    
    
    
private void createMenuBar() {
    JMenuBar menuBar = new JMenuBar();

    // Cria o menu "Menu Principal"
    JMenu menuPrincipal = new JMenu("Menu");

    JMenuItem itemMenu = new JMenuItem("Menu");

    // Adiciona o item de menu ao menu "Menu Principal"
    menuPrincipal.add(itemMenu);

    // Adiciona o menu "Menu Principal" à barra de menu
    menuBar.add(menuPrincipal);

    // Define a barra de menu como a barra de menu da janela
    setJMenuBar(menuBar);

    // Adiciona um ouvinte de ação ao item de menu "Menu"
    itemMenu.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose(); // Fecha a janela atual
            // Aqui você deve adicionar a lógica para abrir a janela do menu principal
            // Supondo que a janela do menu principal seja chamada MenuPrincipal, você pode fazer assim:
            Menu menuPrincipal = new Menu();
            menuPrincipal.setVisible(true); // Exibe a janela do menu principal
        }
    });
}



    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonDELETAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonDELETAR.setText("Delete");
        jButtonDELETAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDELETAR))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonDELETAR)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDELETARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETARActionPerformed
  String nomeFabricanteSelecionado = (String) jComboBox1.getSelectedItem();
        if (nomeFabricanteSelecionado != null && !nomeFabricanteSelecionado.isEmpty()) {
            int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o fabricante?", "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                long idFabricanteSelecionado = fabricanteServices.obterIdFabricantePorNomedelete(nomeFabricanteSelecionado);
if (idFabricanteSelecionado != -1) {
    fabricanteServices.deletarFabricante(idFabricanteSelecionado);
    preencherComboBox();
    JOptionPane.showMessageDialog(this, "Fabricante deletado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
} else {
    JOptionPane.showMessageDialog(this, "Nome do fabricante não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
}

            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um fabricante para deletar.", "Nenhum fabricante selecionado", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonDELETARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletarFabricante().setVisible(true);
            }
        });
    }

    
    
    
    

 
 
  private void preencherComboBox() {
        List<String> nomesFabricantes = fabricanteServices.obterNomesFabricantesString();
        jComboBox1.removeAllItems();
        for (String nomeFabricante : nomesFabricantes) {
            jComboBox1.addItem(nomeFabricante);
        }
    }

    private void exibirNomeFabricanteSelecionado() {
        String nomeFabricanteSelecionado = (String) jComboBox1.getSelectedItem();
    }

    public class Fabricante {
        private Long id;
        private String nome;

        private Fabricante(long idFabricanteSelecionado, String nomeFabricanteSelecionado) {
            this.id = idFabricanteSelecionado;
            this.nome = nomeFabricanteSelecionado;
        }

        public Long getId() {
            return id != null ? id : -1L; // Retorna -1 se o ID for nulo
        }
    }

    
    private void setBackgroundImage() {
    // Caminho absoluto para a imagem
    String imagePath = "C:\\Users\\Rodrigo Ortolani\\Documents\\NetBeansProjects\\Locadora-de-Ve-culos-main\\app\\src\\main\\java\\Locadora\\View\\Imagens\\editar.jpg";


    try {
        // Carrega a imagem
        Image image = new ImageIcon(imagePath).getImage();

        // Verifica se a imagem foi carregada corretamente
        if (image != null) {
            // Redimensiona a imagem para caber no JFrame
            int contentWidth = getContentPane().getWidth();
            int contentHeight = getContentPane().getHeight();
            Image scaledImage = image.getScaledInstance(contentWidth, contentHeight, Image.SCALE_SMOOTH);

            // Cria um ImageIcon com a imagem redimensionada
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            // Cria um JLabel para exibir a imagem
            JLabel backgroundLabel = new JLabel(scaledIcon);
            backgroundLabel.setBounds(0, 0, contentWidth, contentHeight);

            // Adiciona o JLabel ao content pane do JFrame
            getContentPane().add(backgroundLabel);

            // Revalida e redesenha o content pane do JFrame para garantir que as mudanças sejam aplicadas
            revalidate();
            repaint();
        } else {
            System.err.println("Erro ao carregar a imagem: " + imagePath);
        }
    } catch (Exception e) {
        e.printStackTrace();
        System.err.println("Erro ao carregar a imagem: " + imagePath);
    }
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDELETAR;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
