/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Locadora.View;

import Locadora.Model.Fabricante;
import Locadora.Services.FabricanteServices;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Rodrigo Ortolani
 */
public class EditarFabricante extends javax.swing.JFrame {

    
            private final FabricanteServices fabricanteServices;


    
    
    public EditarFabricante() {
        initComponents();
           setBackgroundImage(); 
       createMenuBar();
        
          setLocationRelativeTo(null); // Define a posição da janela para o centro da tela
        setResizable(false);
    
            fabricanteServices = new FabricanteServices();
        preencherComboBox();
        
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exibirNomeFabricanteSelecionado();
            }
        });
        
        
        
        
    }

    
    
    
private void createMenuBar() {
    JMenuBar menuBar = new JMenuBar();

    // Cria o menu "Menu Principal"
    JMenu menuPrincipal = new JMenu("Menu");

    JMenuItem itemMenu = new JMenuItem("Menu");

    // Adiciona o item de menu ao menu "Menu Principal"
    menuPrincipal.add(itemMenu);

    // Adiciona o menu "Menu Principal" à barra de menu
    menuBar.add(menuPrincipal);

    // Define a barra de menu como a barra de menu da janela
    setJMenuBar(menuBar);

    // Adiciona um ouvinte de ação ao item de menu "Menu"
    itemMenu.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose(); // Fecha a janela atual
            // Aqui você deve adicionar a lógica para abrir a janela do menu principal
            // Supondo que a janela do menu principal seja chamada MenuPrincipal, você pode fazer assim:
            Menu menuPrincipal = new Menu();
            menuPrincipal.setVisible(true); // Exibe a janela do menu principal
        }
    });
}



    
    
    

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        TEXTNOMEFABRICANTE = new javax.swing.JTextField();
        BTNEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        TEXTNOMEFABRICANTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTNOMEFABRICANTEActionPerformed(evt);
            }
        });

        BTNEditar.setText("Editar");
        BTNEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTNOMEFABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNEditar))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TEXTNOMEFABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNEditar)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TEXTNOMEFABRICANTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTNOMEFABRICANTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTNOMEFABRICANTEActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        
        
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BTNEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditarActionPerformed
        
        String nomeFabricanteSelecionado = (String) jComboBox1.getSelectedItem();
    String novoNomeFabricante = TEXTNOMEFABRICANTE.getText();

    if (novoNomeFabricante.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite o novo nome do fabricante.");
        return;
    }

    Fabricante fabricante = new Fabricante();
    fabricante.setNome(nomeFabricanteSelecionado);
    fabricante.setNovoNome(novoNomeFabricante);

    fabricanteServices.editarFabricante(fabricante);
    preencherComboBox();
    JOptionPane.showMessageDialog(this, "Fabricante editado com sucesso!");
        
        
        
        
    }//GEN-LAST:event_BTNEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarFabricante().setVisible(true);
            }
        });
    }
 private void preencherComboBox() {
        List<String> nomesFabricantes = fabricanteServices.obterNomesFabricantesString();
        jComboBox1.removeAllItems();
        for (String nomeFabricante : nomesFabricantes) {
            jComboBox1.addItem(nomeFabricante);
        }
    }
 
 
  private void exibirNomeFabricanteSelecionado() {
        String nomeFabricanteSelecionado = (String) jComboBox1.getSelectedItem();
        TEXTNOMEFABRICANTE.setText(nomeFabricanteSelecionado);
    }

    private void editarFabricante() {
        String nomeFabricanteSelecionado = (String) jComboBox1.getSelectedItem();
        String novoNomeFabricante = TEXTNOMEFABRICANTE.getText();

        if (novoNomeFabricante.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o novo nome do fabricante.");
            return;
        }

        Fabricante fabricante = new Fabricante();
        fabricante.setNome(nomeFabricanteSelecionado);
        fabricante.setNome(novoNomeFabricante);

        fabricanteServices.editarFabricante(fabricante);
        preencherComboBox();
        JOptionPane.showMessageDialog(this, "Fabricante editado com sucesso!");
    }
 
 
 private void setBackgroundImage() {
    // Caminho absoluto para a imagem
    String imagePath = "C:\\Users\\Rodrigo Ortolani\\Documents\\NetBeansProjects\\Locadora-de-Ve-culos-main\\app\\src\\main\\java\\Locadora\\View\\Imagens\\editar.jpg";


    try {
        // Carrega a imagem
        Image image = new ImageIcon(imagePath).getImage();

        // Verifica se a imagem foi carregada corretamente
        if (image != null) {
            // Redimensiona a imagem para caber no JFrame
            int contentWidth = getContentPane().getWidth();
            int contentHeight = getContentPane().getHeight();
            Image scaledImage = image.getScaledInstance(contentWidth, contentHeight, Image.SCALE_SMOOTH);

            // Cria um ImageIcon com a imagem redimensionada
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            // Cria um JLabel para exibir a imagem
            JLabel backgroundLabel = new JLabel(scaledIcon);
            backgroundLabel.setBounds(0, 0, contentWidth, contentHeight);

            // Adiciona o JLabel ao content pane do JFrame
            getContentPane().add(backgroundLabel);

            // Revalida e redesenha o content pane do JFrame para garantir que as mudanças sejam aplicadas
            revalidate();
            repaint();
        } else {
            System.err.println("Erro ao carregar a imagem: " + imagePath);
        }
    } catch (Exception e) {
        e.printStackTrace();
        System.err.println("Erro ao carregar a imagem: " + imagePath);
    }
}
    
 
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEditar;
    private javax.swing.JTextField TEXTNOMEFABRICANTE;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
